edition: 1.0.0

services:
  my-service:
    component: "devsapp/fc"
    description: "Service for running code.py from GitHub"
    internetAccess: true

    props:
      region: "cn-hangzhou"
      service:
        name: "my-service"
      function:
        name: "my-function"
        description: "Function to run code.py from GitHub"
        runtime: python3.10
        handler: index.handler
        memorySize: 512
        timeout: 300
        codeUri: "./"  # 使用相对路径指向当前目录
        environmentVariables:
          ENV_VAR: "value"
        layers:
          # - 5229f5451128478bf8616e3b0357e5fb#layer1#1
          - acs:fc:cn-hangzhou:1843118179709723:layers/layer1/versions/1

      events:
        - httpTrigger:
            method: GET
            path: /run-code

triggers:
  httpTrigger:
    type: http
    config:
      authType: anonymous
      methods: ["GET"]
