edition: 1.0.0

services:
  my-service:
    component: "devsapp/fc"
    description: "Service for running code.py from GitHub"
    internetAccess: true

    props:
      region: "cn-hangzhou"
      service:
        name: "my-service"
      function:
        name: "my-function"
        description: "Function to run code.py from GitHub"
        runtime: python3
        handler: index.handler
        memorySize: 512
        timeout: 300
        codeUri: "./"
        environmentVariables:
          ENV_VAR: "value"
        customContainerConfig:
          image: "registry.cn-hangzhou.aliyuncs.com/your_registry/your_image"  # 替换为你的自定义容器镜像
        layers:  # 如果不使用自定义容器，可以使用层来管理依赖
          - name: python_dependencies
            version: 1

        events:
          - httpTrigger:
              method: GET
              path: /run-code

triggers:
  httpTrigger:
    type: http
    config:
      authType: anonymous
      methods: ["GET"]
