edition: 1.0.0

services:
  my-service:
    component: "devsapp/fc"
    description: "Service for running code.py from GitHub"
    internetAccess: true

    props:
      region: "cn-hangzhou"
      service:
        name: "my-service"
      function:
        name: "my-function"
        description: "Function to run code.py from GitHub"
        runtime: python3
        handler: index.handler
        memorySize: 512
        timeout: 300
        codeUri: "./"  # 使用相对路径指向当前目录
        environmentVariables:
          ENV_VAR: "value"
        layers:
          - arn:acs:fc:cn-hangzhou:123456789012:layers/layer1/1  # 替换为实际的 ARN

      events:
        - httpTrigger:
            method: GET
            path: /run-code

triggers:
  httpTrigger:
    type: http
    config:
      authType: anonymous
      methods: ["GET"]
